### ISSUE TITLE
npm run build error Windows 10

### ISSUE THREAD

**Issue by DmytroStognii** [magento-research/pwa-studio#756] opened 2019-01-14 14:34 UTC
## This issue is for the following packages:

- [ ] `venia-concept`
- [ x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | Windows 10 |
| node.js version (`node -v`) | 10.15.0 |
| npm version (`npm -v`)      | 5.8.0 |

## Description

Hi all! I'm trying to run 'npm run build' and getting error:

@magento/pwa-buildpack: src/magento-layout-loader/__tests__/__fixtures__/only-entry/index.js: Unexpected token (4:11)
lerna ERR! npm run build -s exited 1 in '@magento/pwa-buildpack'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magento/pwa-studio@2.0.0 build: `npx lerna run --stream build -- -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magento/pwa-studio@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Expected result:

npm run build should be executed without any errors.

## Possible solutions:

**Comment by mpopov** [comment] 2019-01-20 19:45
Having the same issue

**Comment by tjwiebell** [comment] 2019-05-31 21:49
Duplicate of #898. We suggest Windows users use Docker in the meantime, instructions can be found here:

https://github.com/magento-research/pwa-studio/tree/develop/docker

**Closed by tjwiebell** 2019-05-31 21:49 UTC
Labels: bug

**Comment by hkdAdminHkGithub** [comment] 2019-10-07 22:54
hmm
