### ISSUE TITLE
 "Update Cart" button does not work on Edit Cart Item right drawer.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#818] opened 2019-02-05 02:29 UTC
Description:
"Update Cart" button does not work Edit Cart Item right drawer/panel.

1. Go to Venia storefront and a add product to cart.
2. Now click on edit item option present under more options (3 vertical dots).
3. Click on update Cart button.

Expected behavior:
Shopping Cart right drawer should be displayed with updated attributes(qty/color/size) if any.

Actual:
Update Cart button is dead, nothing happens after clicking.

Screen:
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/2d602682-f12e-44f9-8b6b-309d9b14ce13)

**Comment by tjwiebell** [comment] 2019-02-08 17:51
Duplicate of #665

**Closed by tjwiebell** 2019-02-08 17:51 UTC
Labels: bug
