### ISSUE TITLE
[BUG] User is not able to enter child category using direct URL

### ISSUE THREAD

**Issue by creatuitydevelopers** [magento-research/pwa-studio#914] opened 2019-02-19 08:18 UTC
**Describe the bug**
Venia does not support nested categories right now. Navigation works correctly but when I use direct URL to 2nd (and lower) level category I get 404 error. It is hard to recreate this issue on PWA preview as there are no nested categories.

**To Reproduce**
1. Copy direct URL to any child category.
2. Try to go to this category using a direct URL.
3. 404 error appears.

**Expected behavior**
User should be able to navigate to any category using direct URL.

**Screenshots**
![nested-category-page](https://user-images.githubusercontent.com/1653168/52999836-1d36a480-3427-11e9-875c-9d83722e9871.png)

**Please complete the following device information:**
 - Device: All devices
 - OS: All OSs
 - Browser: All browsers
 - Magento Version: 2.3.0
 - NPM version `npm -v`
 - Node Version `node -v`

**Please let us know what packages this bug is in regards to:**
- [ / ] `venia-concept`

**Additional context**
This issue appeared after the most recent update of Venia.

**Comment by herobk** [comment] 2019-04-07 04:28
I face this problem too.
Did you have any solution for it ?

**Comment by tjwiebell** [comment] 2019-05-31 22:07
Duplicate of #1256 (has a PR up already, just waiting to merge).

**Closed by tjwiebell** 2019-05-31 22:07 UTC
Labels: bug
