### ISSUE TITLE
Documentation for PaymentRequest POC

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#82] opened 2018-06-22 20:00 UTC
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[X] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Documentation support for upcoming PaymentRequest POC for Checkout experience. Discovery to consider this as an example and separate (navigation) from rest of PWA documentation as an example but leaving detail to technical writer.

## Expected result:

Documentation updates with an overview of PaymentRequest POC including integration and cross-referencing to Magento 2 REST API
Peer and technical review (as appropriate)

**Comment by jcalcaben** [comment] 2018-07-03 19:30
@ericerway is this a duplicate of #78 or something different entirely?

**Comment by ericerway** [comment] 2018-07-03 19:44
@jcalcaben related but different; PaymentRequest work builds on top of this which we're developing for this sprint. You're blocked until it is developed so may push to next sprint.

**Comment by ericerway** [comment] 2018-07-13 20:23
Moving to next sprint with PR dependency; some progress related to #78.

**Comment by awilcoxa** [comment] 2019-02-20 16:41
Closing as complete

**Closed by awilcoxa** 2019-02-20 16:41 UTC
Labels: pkg:pwa-devdocs
