### ISSUE TITLE
error code ELIFECYCLE

### ISSUE THREAD

**Issue by syedsaleem086** [magento-research/pwa-studio#810] opened 2019-02-04 04:50 UTC
**Always getting above error tried to resolve using these methods**
`npm cache clean --force`
delete `node_modules` folder
created empty directory `node_modules` and given full permission
`chmod -R a+rwx ./node_modules `

**To Reproduce**
Ubuntu 18.04
Use NVM to install Nodejs
use the latest LTS Edition 10.15.1
Clone this repository using git

**Expected behavior**
Should complete without error

**Please complete the following device information:**
 - Device: [e.g. iPhone6, PC]
 - OS: Ubuntu 18.04
 - Magento Version : 2.3.0
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: 10.15.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Error  log**
...
...
...
33340 silly saveTree |       +-- exit-hook@1.1.1
33340 silly saveTree |       `-- onetime@1.1.0
33340 silly saveTree +-- prettier-check@2.0.0
33340 silly saveTree | `-- execa@0.6.3
33340 silly saveTree |   `-- cross-spawn@5.1.0
33340 silly saveTree +-- prettier@1.15.3
33340 silly saveTree +-- stream-snitch@0.0.3
33340 silly saveTree `-- wait-for-expect@1.1.0
33341 warn jest-transform-graphql@2.1.0 requires a peer of graphql-tag@^2.0.0 but none is installed. You must install peer dependencies yourself.
33342 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
33343 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
33344 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
33344 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
33344 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
33344 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
33345 verbose stack Error: iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
33345 verbose stack Exit status 126
33345 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
33345 verbose stack     at EventEmitter.emit (events.js:189:13)
33345 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
33345 verbose stack     at ChildProcess.emit (events.js:189:13)
33345 verbose stack     at maybeClose (internal/child_process.js:970:16)
33345 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
33346 verbose pkgid iltorb@1.3.10
33347 verbose cwd /var/www/html/magento23/pwa-studio
33348 verbose Linux 4.15.0-45-generic
33349 verbose argv "/root/.nvm/versions/node/v10.15.1/bin/node" "/root/.nvm/versions/node/v10.15.1/bin/npm" "install"
33350 verbose node v10.15.1
33351 verbose npm  v6.4.1
33352 error code ELIFECYCLE
33353 error errno 126
33354 error iltorb@1.3.10 install: `detect-libc prebuild-install || node-gyp rebuild`
33354 error Exit status 126
33355 error Failed at the iltorb@1.3.10 install script.
33355 error This is probably not a problem with npm. There is likely additional logging output above.
33356 verbose exit [ 126, true ]

**Comment by tjwiebell** [comment] 2019-02-11 18:38
Duplicate of #820, and in process of delivering fix in #864 (make all binary dependencies optional).

**Closed by tjwiebell** 2019-02-11 18:38 UTC
Labels: bug, duplicate
