### ISSUE TITLE
[BUG] https://pwastudio.io is not redirected

### ISSUE THREAD

**Issue by DanielRuf** [magento-research/pwa-studio#995] opened 2019-03-05 19:36 UTC
**Describe the bug**
https://pwastudio.io does not redirect but http://pwastudio.io does

**To Reproduce**
1. Go to https://pwastudio.io

**Expected behavior**
The URL should be redirected.

**Please complete the following device information:**
 - Device: [e.g. iPhone6, PC]
 - OS: [e.g. iOS8.1, Windows 10]
 - Magento Version
 - NPM version `npm -v`
 - Node Version `node -v`

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [x] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**

**Comment by sirugh** [comment] 2019-03-14 18:37
This is because the certificate is invalid. We will need to fix this, thanks!

**Comment by mhhansen** [comment] 2019-03-16 12:33
thanks for filling this out @DanielRuf !
closing, since it seems to be resolved. please reopen if trouble persists.
certificate now shows renewed and redirect is currently working

**Comment by DanielRuf** [comment] 2019-03-16 13:14
It is not resolved. The new certificate is not used as it seems.

https://www.ssllabs.com/ssltest/analyze.html?d=pwastudio.io&hideResults=on&ignoreMismatch=on&latest

**Comment by mhhansen** [comment] 2019-03-16 13:42
You're right Daniel, mistyped when test/checked early this morning, my fault!

**Comment by DanielRuf** [comment] 2019-03-16 13:46
You can see the known certs at https://crt.sh/?q=pwastudio.io and check if browsers see it then.

**Comment by ericerway** [comment] 2019-03-27 15:13
SSL and redirect fixed with hosting provider. Please verify. Thanks!

**Comment by supernova-at** [comment] 2019-03-27 15:18
Confirmed that both https://pwastudio.io and http://pwastudio.io redirect appropriately.

**Closed by supernova-at** 2019-03-27 15:18 UTC
Labels: bug
