### ISSUE TITLE
[bug]: there is an error says "ERROR in ./FETCH_ROOT_COMPONENT,Module not found: Error: Can't resolve 'srcRootComponentsCMSindex.js'" happen when run the yarn run build

### ISSUE THREAD

**Issue by vocaloid123** [magento-research/pwa-studio#1255] opened 2019-05-20 06:11 UTC
**Describe the bug**

there is an error says "ERROR in ./FETCH_ROOT_COMPONENT,Module not found: Error: Can't resolve 'srcRootComponentsCMSindex.js'" happen when run  the yarn run  build

**To Reproduce**

1. Go to pwastudio root project
2. run yarn run build
3. when build the venia-concept packages,there is an error says "ERROR in ./FETCH_ROOT_COMPONENT,Module not found: Error: Can't resolve 'srcRootComponentsCMSindex.js'" in 'D:\pwastudio\packages\venia-concept'

**Screenshots**

![image](https://user-images.githubusercontent.com/24838615/57999601-869e8000-7b08-11e9-90bb-800f1a289b5b.png)

**Please complete the following device information:**
 - Device :PC
 - OS :Windows 10
 - Magento Version:2.31
 - PWA Studio Version:2.1.0
 - NPM version `npm -v`:6.4.1
 - Node Version `node -v`:v10.15.3

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`

**Comment by tjwiebell** [comment] 2019-05-31 20:37
Duplicate of #898. We suggest Windows users use Docker in the meantime, instructions can be found here:

https://github.com/magento-research/pwa-studio/tree/develop/docker

**Closed by tjwiebell** 2019-05-31 20:37 UTC
Labels: bug

**Comment by koushikch7** [comment] 2020-02-19 10:16
@tjwiebell Seems to be Searching for the alternative is not the solution rather than fixing the issue! what you say?

**Comment by ivoruumz** [comment] 2020-02-21 15:33
@vocaloid123 I have the same problem. Have you find a solution?
