### ISSUE TITLE
User friendly error message is not displayed on clicking sign-in button after entering invalid details.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#819] opened 2019-02-05 02:51 UTC
Description:
User friendly error message is not displayed on clicking sign-in button after entering invalid details.

1. Go to Venia storefront and Click on sign In button on Main menu (Left drawer).
2. Enter valid email and invalid password and click on Sign-in Button.

Expected :
User should just see invalid inputs related error message.

Actual:
User is shown with so much error details like api call, PHP stack trace etc.

Screen :

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/edb80edf-3195-404a-8f33-3841a768914d)

**Comment by zetlen** [comment] 2019-02-05 19:31
Duplicate of #735.

**Comment by tjwiebell** [comment] 2019-05-31 22:02
This appears to be fixed, closing.

<img width="340" alt="Screen Shot 2019-05-31 at 5 02 26 PM" src="https://user-images.githubusercontent.com/462953/58737106-ea0c9580-83c5-11e9-9e50-7511ef2d485e.png">

**Closed by tjwiebell** 2019-05-31 22:02 UTC
Labels: bug
