### ISSUE TITLE
Spike: Research E2E testing, with MFTF if possible

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#191] opened 2018-07-31 21:10 UTC
[Jest](https://jestjs.io) is for unit testing, and for integration testing of multiple functional units, but it isn't an end-to-end testing system on the order of [Magento Functional Test Framework](https://github.com/magento/magento2-functional-testing-framework). We must explore integration of such a framework.

**Comment by zetlen** [comment] 2018-10-16 14:54
@vitalics Let's use this issue for a permanent record of discussion about functional testing. I'm going to reproduce your comments from Slack here.

**Comment by zetlen** [comment] 2018-10-16 15:09
> **Vitali Haradkou**: Hey James, I just have some purpose about testing strategy.   I suggest using .feature files for BDD testing because at the start of this week we are not selected strategy. On the other hand, we can use the protractor(JS automation), in order to integrate with feature files, local mobile testing out-of-box. We don't need to create the private repo that forking Magento. We just can add another module for existing packages, for example, pwa-e2e. This allows us to focus on an open-source
>here is a simple example of the feature file.
>I Also attached file for your detailed review.
>You can see that this file is easy to read not only for a technical person but the non-techical person(i.e manager) can see what happens with this test, what steps are included and what can be added.
>This is the reason for using js automation. Cucumber is an open source project.
>It supports only Java, Ruby, and JS.
>For throw lighting, I also attached the link for Cucumber docs. https://docs.cucumber.io/guides/overview/
```gherkin
Feature: Authorization
  Scenario: Sign In
    Given Anonimous User
    When User click by "sign in" button
    Then User presented "SIGN IN" form
    And User fill "Email" field
    And User fill "password" field
    And User submit "sign in" form
    And User see email on the buttom
  Scenario: Sign Up
    Given Anonimous User
    When User click by "sign in" button
    Then User presented "SIGN IN" form
    And User click by "Create an Account" button
    Then User presented "CREATE ACCOUNT" form
    And User fill "First name" field
    And User fill "Last name" field
    And User fill "Email" field
    And User fill "Password" field
    And User fill "Confirm Password" field
    And User submit "sign up" form
  Scenario: Forgot Password
    Given Anonimous User
    When User click by "sign in" button
    Then User presented "SIGN IN" form
    And User click by "Forgot your username or password?" button
    And User fill "Email address" field
    And User submit "forgot password" form
    And User click by "Continue shopping" button
  Scenario Outline: Many users signing in
    Given Anonimous User
    When User click by "sign in/sign up" button
    Then Side menu is visible
    And User presented authorization form
    And User submit authorization form with <Username> and <Password>
    And User see email on the topbar
    Examples:
      | Id | Username | Password    |
      | 1 | user1  | user1_password |
      | 2 | user2  | user2_password |
      | 3 | user3  | user3_password |
```

**Comment by zetlen** [comment] 2018-10-16 15:12
> **James Zetlen**: My concern is that these still must be executed by a WebDriver, and someone must write accessors for things like `"Email" field`.
>
>Traditionally in Selenium this is done with XPath, but that doesn't work very well for React apps
Because React apps are not guaranteed to build a specific DOM tree. We often use third-party components as dependencies. When we update a dependency, even to a minor patch version, the DOM structure of that third-party component may change. It wouldn't violate our semver expectations as frontend developers, because its visual display and its React component API would be the same. 
>
>But an XPath query would fail.
>
>I know you can use CSS selectors like jQuery as well, and that's what I would do instead, but you must use complex selectors, because the classnames are autogenerated.

**Comment by vitalics** [comment] 2018-10-16 19:59
I agree with you about `React DOM` and third-party componentsand libs, but in same time MFTF - is the just a wrapper for Webdriver, also as the protractor. MFTF use only the Magento's components for testing, but in our case, we are totally implementing pages from nothing(this is not a Magento default page, we are creating new pages with rules(e.g. router, redirects)), we haven't Magento's components. it can over cost of extending existing MFTF components(such as list, block).
To start do it with JS you only need the nodejs on your local machine/server, but in case of MFTF you will needed a full copy of Magento + to get a token from instance + have a php, mysql and local instance of Magento. It has been taking me a lot of time to start configure all of this Magento environment

**Comment by antonkril** [comment] 2018-10-24 17:14
@vitalics can you please clarify why did you need running instance of Magento locally? By design MFTF must not require local instance of Magento. Any such dependency should be considered a bug in MFTF.

Main feature of MFTF is extensibility. It allows Magento extension developers to extend testsuites similarly to how they extend Magento. This feature MUST be supported by any E2E testing solution we use for PWA

**Comment by vitalics** [comment] 2018-10-26 10:50
@zetlen @ericerway blocked by questions related to MFTF

**Comment by awilcoxa** [comment] 2019-02-19 18:37
closing during backlog cleanup, moving forward @dpatil-magento will be evaluating/building plan for MFTF coverage and PWA

**Closed by awilcoxa** 2019-02-19 18:37 UTC

**Comment by dpatil-magento** [comment] 2019-02-19 18:40
Currently MFTF tests are being added to https://github.com/magento-research/pwa-tests
