### ISSUE TITLE
[bug]: Unable to access nested categories via direct URL

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1208] opened 2019-05-07 14:36 UTC
Pre-condition- 
Sample data with nested categories available on Venia.

Steps - 
1. On Venia store front access nected category via direct URL. example: https://magento-venia-xytiqkwfoi.now.sh/venia-bottoms/venia-skirts.html  

Expected - Nested or Sub category page should load with products.
Actual - Page does not load, user always see example: "Loading Skirts"

Note - Works fine if user access by clicking sub category via main menu.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/7dfc0bd1-e9a2-43c4-8062-16f192e284e7)

**Comment by awilcoxa** [comment] 2019-05-08 14:42
Replicated by going directly to a nested category URL, the use case doesn't seem clear to me (what user is trying to access category URL directly in browser) but at the same time this is a real issue. 

Moving to for grooming for future prioritization.

**Comment by BogusKrzysztof** [comment] 2019-05-15 07:50
Changing 
`{{#bundles.load}}
    <script defer src="{{.}}"></script>
{{/bundles.load}}`
to
`{{#bundles.load}}
    <script defer src="/{{.}}"></script>
{{/bundles.load}}`
In pwa-studio/packages/venia-concept/templates/seed-bundles.mst seems to resolve this issue.

**Comment by awilcoxa** [comment] 2019-06-03 15:50
closing as dupe of #1257

**Closed by awilcoxa** 2019-06-03 15:50 UTC
Labels: bug
