### ISSUE TITLE
@magento/venia-drivers not resolving when using VeniaAdapter

### ISSUE THREAD

**Issue by rossmc** [magento-research/pwa-studio#1089] opened 2019-03-30 05:24 UTC
**Describe the bug**
I'm trying to see how I can use Venia components in a simple react app by following the [Modular components docs] and using _Create React App_. But I get two errors, the first I can fix by updating how CSS Modules are configured in my react app, but there is a second error I come to which I can't fix...

```bash
Failed to compile.

./node_modules/@magento/venia-concept/esm/components/CategoryList/categoryList.js
Module not found: Can't resolve '@magento/venia-drivers' in 'my-venia-adapter/node_modules/@magento/venia-concept/esm/components/CategoryList'
```

**To Reproduce**
1. Install a simple React app with create-react-app, eject the webpack configuration and add dependencies for magento, redux & apollo packages.
```bash
npx create-react-app my-venia-adapter
cd my-venia-adapter
yarn eject
yarn add @magento/venia-concept
yarn add redux
yarn add apollo-boost react-apollo graphql --save
```
2. Based on the [venia adapter example in the docs], update the _src/App.js_ file with the following:
```javascript
import React, { Component } from 'react';
import VeniaAdapter from '@magento/venia-concept/esm/drivers/adapter';
import CategoryList from '@magento/venia-concept/esm/components/CategoryList';
import { createStore } from 'redux';
import { ApolloClient } from 'apollo-client';

const myApplicationStore = createStore()
const myClient = new ApolloClient({ uri: "https://veniapwa.com/graphql"})

class App extends Component {
  render() {
    return (
      <VeniaAdapter client={myClient} store={myApplicationStore} apiBase="https://veniapwa.com/graphql">
        <CategoryList title="Shop by category" id={2} />
      </VeniaAdapter>
    );
  }
}

export default App;
```
3. Run the following command:
``` bash
yarn start
Failed to compile.

./node_modules/@magento/venia-concept/esm/components/CategoryList/categoryList.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/@magento/venia-concept/esm/components/CategoryList/categoryList.css)
Error: composition is only allowed when selector is single :local class name not in ".noResults", ".noResults" is weird
    at Array.map (<anonymous>)
```
4. Fix the error above by updating _config/webpack.config.js_
```diff
 // style files regexes
 const cssRegex = /\.css$/;
-const cssModuleRegex = /\.module\.css$/;
+// const cssModuleRegex = /\.module\.css$/;
 const sassRegex = /\.(scss|sass)$/;
 const sassModuleRegex = /\.module\.(scss|sass)$/;
 
@@ -388,23 +388,23 @@ module.exports = function(webpackEnv) {
             // to a file, but in development "style" loader enables hot editing
             // of CSS.
             // By default we support CSS Modules with the extension .module.css
-            {
-              test: cssRegex,
-              exclude: cssModuleRegex,
-              use: getStyleLoaders({
-                importLoaders: 1,
-                sourceMap: isEnvProduction && shouldUseSourceMap,
-              }),
-              // Don't consider CSS imports dead code even if the
-              // containing package claims to have no side effects.
-              // Remove this when webpack adds a warning or an error for this.
-              // See https://github.com/webpack/webpack/issues/6571
-              sideEffects: true,
-            },
+            // {
+            //   test: cssRegex,
+            //   exclude: cssModuleRegex,
+            //   use: getStyleLoaders({
+            //     importLoaders: 1,
+            //     sourceMap: isEnvProduction && shouldUseSourceMap,
+            //   }),
+            //   // Don't consider CSS imports dead code even if the
+            //   // containing package claims to have no side effects.
+            //   // Remove this when webpack adds a warning or an error for this.
+            //   // See https://github.com/webpack/webpack/issues/6571
+            //   sideEffects: true,
+            // },
             // Adds support for CSS Modules (https://github.com/css-modules/css-modules)
             // using the extension .module.css
             {
-              test: cssModuleRegex,
+              test: cssRegex,
               use: getStyleLoaders({
                 importLoaders: 1,
                 sourceMap: isEnvProduction && shouldUseSourceMap,
```
5. Try to start the react app again and see new error:
```bash
yarn start

Failed to compile.

./node_modules/@magento/venia-concept/esm/components/CategoryList/categoryList.js
Module not found: Can't resolve '@magento/venia-drivers' in 'my-venia-adapter/node_modules/@magento/venia-concept/esm/components/CategoryList'
```

**Expected behavior**
To see workable example of the Venia Adapter displaying a Category List from the _@magento/venia-concept_ package, similar to what is seen on the homepage of [veniapwa.com].

**Additional context**
The [Modular components docs] and  [Venia Consumer Example] both suggest an alternative way of using Venia components with **custom drivers**, however I'm trying to get it to work with the Venia Adapter by itself.  Nevertheless I tried to use a custom driver, as described below, but it did not work.

**Possible solutions**
I tried adding a [custom driver from the docs] and also the [driver from the venia consumer example], neither worked and gave the [error described here]. Nevertheless I would prefer to get the VeniaAdapter working rather than use a custom adapter.

**Please complete the following device information:**
- OS X 10.14.1
- Chrome 73.0.3683.86
- node v11.10.1
- yarn v1.13.0
- npm v6.7.0

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

[Modular components docs]: https://magento-research.github.io/pwa-studio/venia-pwa-concept/features/modular-components/
[venia adapter example in the docs]: https://magento-research.github.io/pwa-studio/venia-pwa-concept/features/modular-components/#venia-adapter
[veniapwa.com]: https://veniapwa.com/
[Venia Consumer Example]: https://github.com/magento-research/venia-consumer-example
[custom driver from the docs]: https://magento-research.github.io/pwa-studio/venia-pwa-concept/features/modular-components/#custom-drivers
[driver from the venia consumer example]: https://github.com/magento-research/venia-consumer-example/blob/master/src/veniaDrivers.js
[error described here]: https://github.com/magento-research/venia-consumer-example/issues/1

**Comment by awilcoxa** [comment] 2019-06-24 18:50
this is likely a duplicate of #908. Closing as duplicate but will track against 908.

**Closed by awilcoxa** 2019-06-24 18:50 UTC
Labels: Troubleshoot, bug

**Comment by trung-pham** [comment] 2021-02-19 02:58
Is this issue resolved ?

**Comment by sirugh** [comment] 2021-02-19 14:17
@trung-pham did you check the linked issue? I'd at least move your comment to the non-dup issue if I were you :)

**Comment by trung-pham** [comment] 2021-03-06 10:43
@sirugh I checked the linked issued but it does not provide any lead. Anyway I configured it myself.

**Comment by sirugh** [comment] 2021-03-08 16:17
> @sirugh I checked the linked issued but it does not provide any lead. Anyway I configured it myself.

Great! What did you have to do?
