### ISSUE TITLE
[Bug]: Authorized user cannot add product to cart

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#655] opened 2018-12-12 14:41 UTC
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
Steps to reproduce:
**Precondition**:
- clear all site data such as cookies, service worker cache, etc.
**Steps**:
- in the main page, choose any category, e.g. `shop-the-look`
- choose any product and click them
- open the left menu and click the `sign in` button
- type user credentials (username and password) and click the `sign in` button
- close left menu
- try to click `add to cart` on the currently opened item

- nothing happens, even request for adding on the cart not send

## Expected result:
Request sending and work correctly(add an item to cart)
Cart menu must open after sending a request

**Comment by tungdtisobat** [comment] 2018-12-18 08:18
Hi @vitalics 
It's not implemented yet, but you can implement yourself via rest.

**Comment by dmtrkad** [comment] 2018-12-18 10:17
@ericerway Could you please approve this item i order to be included in our queque ? Moreover, looks like this item more closer to userstories than a bug.

**Comment by awilcoxa** [comment] 2018-12-18 20:53
@dmtrkad item is approved for work. I'll move to ready to start and you can assign to team.

**Comment by Starotitorov** [comment] 2019-01-03 11:33
@jimbo, @supernova-at, could you please review this pull request https://github.com/magento-research/pwa-studio/pull/685. I need to collect feedback from you to proceed with the implementation, there are some open questions that need to be discussed, I wrote you an email.

**Comment by supernova-at** [comment] 2019-02-26 21:32
Closing as duplicate of #845.

**Closed by supernova-at** 2019-02-26 21:32 UTC
