### ISSUE TITLE
Unable to checkout on Mobile device (Iphone SE). Checkout button is hidden.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1098] opened 2019-04-01 18:33 UTC
Description :
User cant complete checkout flow on Iphone SE as Checkout button hides and user cant get to it.

Steps to reproduce: 
1. Go to Venia storefront
2. Add any product to Cart.
3. Try to checkout

Expected :
User should be able to scroll to checkout button.

Actual:
Checkout button is hidden so there is no way user can tap on it.

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

Device - 
Iphone SE

Env - 
https://veniapwa.com/
https://magento-venia.now.sh/

**Comment by dpatil-magento** [comment] 2019-04-01 18:34
#824 Solution might work for this as well.

**Comment by awilcoxa** [comment] 2019-04-29 21:30
duplicate of #1071

**Closed by awilcoxa** 2019-04-29 21:30 UTC
Labels: bug
