### ISSUE TITLE
[Bug]: Add to cart button is not work

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#484] opened 2018-11-09 13:28 UTC
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[X] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
`Add to cart` button is not set item to `cart`. `Upward` return `400` status code. Request and respose available below:
![general request info](https://user-images.githubusercontent.com/8816260/48264762-b410bf80-e43b-11e8-9a3e-acdb05e4fc35.png)
![request payload](https://user-images.githubusercontent.com/8816260/48264798-d276bb00-e43b-11e8-90c8-1e832cd9d75f.png)
![response info](https://user-images.githubusercontent.com/8816260/48264833-ef12f300-e43b-11e8-93c4-78bc77ee7156.png)
full trace: 
``` txt
#0 /app/vendor/magento/module-quote/Model/QuoteRepository/SaveHandler.php(82): Magento\Quote\Model\Quote\Item\CartItemPersister->save(Object(Magento\Quote\Model\Quote\Interceptor), 'You need to cho...')
#1 /app/generated/code/Magento/Quote/Model/QuoteRepository/SaveHandler/Interceptor.php(24): Magento\Quote\Model\QuoteRepository\SaveHandler->save(Object(Magento\Quote\Model\Quote\Interceptor))
#2 /app/vendor/magento/module-quote/Model/QuoteRepository.php(181): Magento\Quote\Model\QuoteRepository\SaveHandler\Interceptor->save(Object(Magento\Quote\Model\Quote\Interceptor))
#3 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\QuoteRepository->save(Object(Magento\Quote\Model\Quote\Interceptor))
#4 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\QuoteRepository\Interceptor->___callParent('save', Array)
#5 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\QuoteRepository\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Quote\Model\Quote\Interceptor))
#6 /app/generated/code/Magento/Quote/Model/QuoteRepository/Interceptor.php(78): Magento\Quote\Model\QuoteRepository\Interceptor->___callPlugins('save', Array, Array)
#7 /app/vendor/magento/module-quote/Model/Quote/Item/Repository.php(92): Magento\Quote\Model\QuoteRepository\Interceptor->save(Object(Magento\Quote\Model\Quote\Interceptor))
#8 /app/vendor/magento/module-quote/Model/GuestCart/GuestCartItemRepository.php(66): Magento\Quote\Model\Quote\Item\Repository->save(Object(Magento\Quote\Model\Quote\Item))
#9 [internal function]: Magento\Quote\Model\GuestCart\GuestCartItemRepository->save(Object(Magento\Quote\Model\Quote\Item))
#10 /app/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#11 /app/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))
#12 /app/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /app/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)
#14 /app/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /app/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)
#16 /app/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /app/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#18 /app/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http\Interceptor->launch()
#19 /app/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#20 {main}
```

## Expected result:
After choosing an item, `cart` must contain this item and checkout button is available

**Comment by zetlen** [comment] 2018-11-09 15:32
Configurable products are not supported yet in `release/2.0`, so this is a duplicate of https://github.com/magento-research/pwa-studio/issues/283.

**Closed by zetlen** 2018-11-09 15:32 UTC
Labels: bug
