### ISSUE TITLE
venia-concept folder produces `DevServerReadyNotifierPlugin is not a constructor` error

### ISSUE THREAD

**Issue by markshust** [magento-research/pwa-studio#274] opened 2018-09-11 17:31 UTC
## This issue is for the following packages:

[ x ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ x ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0-alpha72 |
| Operating System + version  | Debian/Docker |
| node.js version (`node -v`) | 8.11.4 |
| npm version (`npm -v`)      | 5.6.0 |

## Description

Running npm run start from the venia-concept folder produces `DevServerReadyNotifierPlugin is not a constructor` error:

```
root@2803284cb6b4:/var/www/html/pwa-studio/packages/venia-concept# npm run start

> theme-frontend-venia@0.1.1 start /var/www/html/pwa-studio/packages/venia-concept
> webpack-dev-server --progress --color --env.phase development

TypeError: DevServerReadyNotifierPlugin is not a constructor
    at module.exports (/var/www/html/pwa-studio/packages/venia-concept/webpack.config.js:146:13)
    at <anonymous>
```

## Expected result:

I expect `npm run start` to start the webpack dev server without errors.

**Comment by Morgy93** [comment] 2018-09-20 09:03
Same here 


| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3.0-alpha79 |
| Operating System + version  | Ubuntu 18.04.1 LTS |
| node.js version (`node -v`) | v8.12.0 |
| npm version (`npm -v`)      | v6.4.1 |

**Comment by bastsoft** [comment] 2018-09-25 09:52
in package.json "@magento/pwa-buildpack": "*"  and connects version 0.8.2, which should be DevServerReadyNotifierPlugin, but it is not there, probably not properly labeled. The problem is solved if venia-concept/webpack.config.js to prescribe instead of require('@magento/pwa-buildpack'); local version of require('../pwa-buildpack'); but I think this is not the solution you need to reload the npm version

**Comment by awilcoxa** [comment] 2019-02-19 18:40
closing during backlog cleanup

**Closed by awilcoxa** 2019-02-19 18:40 UTC
