### ISSUE TITLE
Symlinks not setup on `npm install` for Ubuntu users

### ISSUE THREAD

**Issue by DrewML** [magento-research/pwa-studio#341] opened 2018-10-09 11:05 UTC
Found during MLEU contribution day. An `npm install` did not properly symlink the `file://` paths to the `packages` folder. Didn't collect too many details, but we should find at least 1-2 other Ubuntu users to see if this is a more widespread problem.

**Comment by zetlen** [comment] 2018-10-09 21:43
I hope that undoing the `lerna link convert` and switching back to `lerna bootstrap` in 7daeade has fixed this. I tested in Ubuntu and couldn't reproduce it. Closing for now...possibly in favor of #347.

**Closed by zetlen** 2018-10-09 21:43 UTC
Labels: setup help
