### ISSUE TITLE
[bug]: Checkout and other buttons obscured due to 100% viewport calculation in modern mobile browsers

### ISSUE THREAD

**Issue by zetlen** [magento-research/pwa-studio#1114] opened 2019-04-04 19:24 UTC
**Describe the bug**

**To Reproduce**
1. On a device running a late mobile OS, visit veniapwa.com.
2. Add any product to the cart.
3. Look for the checkout button.
4. Touch the extreme left of the screen and attempt to scroll up or down

**Expected behavior**
The cart should adjust its height to be 100% of the visible viewport.

**Screenshots**
![image](https://user-images.githubusercontent.com/1643758/55581809-714dcd80-56e3-11e9-90c5-21c65c9f8496.png)
![image](https://user-images.githubusercontent.com/1643758/55581879-9d694e80-56e3-11e9-8386-3760025e439d.png)

**Additional context**
Modern browser frames expand and contract in response to gestures. They also have partial transparency, which requires rendering a portion of the viewport under them. Layouts like flex and grid often expect to calculate their interior dimensions using the exact viewport height, so this measurement is very important. Browser vendors have conferred about it, and have settled on using the [largest measurement](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/) possible, which is a more broadly compatible, if imperfect, solution.

**Possible solutions**
- A Peregrine hook to subscribe full-height elements to resize events and measure `window.innerHeight` (@jimbo may have input on whether this fits Peregrine's new roadmap)
- Using overflow-y: scroll wherever possible
- Placing call-to-action elements like buttons within a more restricted area of the viewport, like TV production uses a [safe area](https://en.wikipedia.org/wiki/Safe_area_(television)#Action_safe_area) for important content

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment] 2019-04-04 19:25
Related to #1098 and #842.

**Comment by ericerway** [comment] 2019-04-04 19:26
Appears to be a duplicate of #1071 -- should we consolidate?

**Closed** 2019-04-18 11:49 UTC
Labels: bug
