### ISSUE TITLE
[bug]: Yarn build has "Error: Cannot find module ‘../../../magento-compatibility’"

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#1233] opened 2019-05-10 20:25 UTC
Steps -
1. Run Yarn Install for develop branch.
2. Run Yarn Build 

Expected - Build should be successful without any errors.
Actual - Build is successful but with errors. pwa-studio/packages/venia-concept/node_modules/graphql-cli-validate-magento-pwa-queries plugin:Error: Cannot find module ‘../../../magento-compatibility’

**Comment by zetlen** [comment] 2019-05-20 18:00
Can no longer reproduce on 841ec0a2. Are you able to reproduce?

**Comment by zetlen** [comment] 2019-05-20 18:01
@dpatil-magento Cannot reproduce on 841ec0a2. Closing, but please reopen if you can still reproduce it.

**Closed by zetlen** 2019-05-20 18:01 UTC
Labels: bug
