### ISSUE TITLE
Create Account page form input style issue

### ISSUE THREAD

**Issue by codeAdrian** [magento-research/pwa-studio#721] opened 2019-01-03 13:13 UTC
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3 |
| Operating System + version  | macOS 10.13.6 |
| node.js version (`node -v`) | v8.11.3 |
| npm version (`npm -v`)      | 5.6.0 |

## Description

Text inputs on Create Account page are not full width.

![screen shot 2019-01-03 at 2 09 51 pm](https://user-images.githubusercontent.com/11479290/50639374-8dfe2c00-0f61-11e9-879d-cc9b58642266.png)

## Expected result:

Inputs should be full width of the container.

## Possible solutions:

Set the input width to 100%.

**Comment by Starotitorov** [comment] 2019-01-03 14:41
I can take a look, the issue is also related to Create Account form inside navigation drawer. The issue appeared after adding new TextInput component to the form.

**Comment by awilcoxa** [comment] 2019-02-19 19:22
closing during backlog cleanup, PR is merged and appears to have resolved.

**Closed by awilcoxa** 2019-02-19 19:22 UTC
