### ISSUE TITLE
Implement recent orders section on account details page

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#573] opened 2018-11-30 13:58 UTC
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[x] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Implement recent orders section on account details page https://github.com/magento-research/pwa-studio/issues/514. We need to finish the implementation of https://github.com/magento-research/pwa-studio/issues/506.

**Comment by Starotitorov** [comment] 2019-01-03 13:08
It is required to implement required endpoints https://github.com/magento-research/pwa-studio/issues/506 to start the implementation

**Comment by awilcoxa** [comment] 2019-06-10 15:32
closing as dupe of #294

**Closed by awilcoxa** 2019-06-10 15:32 UTC
Labels: hold
