### ISSUE TITLE
[FEATURE] Toasts.

### ISSUE THREAD

**Issue by sirugh** [magento-research/pwa-studio#783] opened 2019-01-24 16:35 UTC
**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Is your feature request related to a problem? Please describe.**
The banner used to display online/offline text currently exists as a component that displays some text related specifically to whether the app is functioning in online or offline mode. It does not allow for any other text.

**Describe the solution you'd like**
The toast/notification banner is useful as a generic component powered by some sort of event system in which components throughout the app could say something like `displayToast(type, message)` and the toast component would handle the display.

Some considerations for dev/ux:

* What states do we care about? Will "info" and "error" suffice or do we need warning, error, etc?
* How do we want to handle multiple toasts emitted at once? **Per advice on material and spectrum, never display multiple at once, queue and display once at a time.**
* How do we want to handle dismissal? Should they be on a timer? Should the user be able to dismiss manually? **Probably both. Soumya will provide mocks.**
* Should we power this via redux/context or use React Portals? **[Here's](https://codesandbox.io/s/qzn5om4y5q) an example using React Hooks.**
* How do we key the list of messages displayed? **timestamp**
* We should be conscious of a11y such as tab/keyboard nav and voiceover.

**Mocks**

[![Image from Gyazo](https://i.gyazo.com/b17131ae4473b25366c7973c71e975e6.png)](https://gyazo.com/b17131ae4473b25366c7973c71e975e6)

(more coming later from @soumya-ashok)

**Additional context**

https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/components/App/app.js#L26

https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/components/OnlineIndicator/onlineIndicator.js

https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/components/OnlineIndicator/onlineIndicator.css

https://codesandbox.io/s/w60xo8o3k7

**Comment by soumya-ashok** [comment] 2019-01-31 17:42
@jimbo and @sirugh 
**Initial design for toasts:**

- User dismissed messages have the X icon to the right.
- Time dismissed messages have a related icon on the left.
- Action messages can be dismissed by clicking the action link, or ignored by clicking the X.

_We haven't determined if and what cases will call for an ignored message to be resurfaced, what the time interval should be to resurface after they are ignored etc._

If there are multiple toasts appearing at the same time, they are displayed with a faux "stacked treatment"

- They bring the number of notifications to the user's attention
- All messages in a stack are dismissible by the user
- Dismissing the top message reveals the message below
- The stacked look persists until the user reaches the last message

_If there is a message with an action link in the stack, and the user clicks the action link, does the stack persist even if the action causes them to leave the screen they are on? Or should we collapse the stack and provide a way for them to recall it?_

**Positive messages:**

![screen shot 2019-01-30 at 3 30 34 pm](https://user-images.githubusercontent.com/25960021/52072973-eb2ed280-254b-11e9-9b70-755e775f93c1.png)

**Negative messages**

![screen shot 2019-01-30 at 3 31 02 pm](https://user-images.githubusercontent.com/25960021/52072998-ff72cf80-254b-11e9-8c51-c1c8461e7ddd.png)

**Multiple toasts at once**

![screen shot 2019-01-31 at 11 34 05 am](https://user-images.githubusercontent.com/25960021/52073058-2d581400-254c-11e9-8d3f-8d8f01c4bae5.png)

**Comment by belbiy** [comment] 2019-01-31 18:15
@soumya-ashok , i like the overall clean aesthetic. But i feel the border separating the body of the toast and dismiss/icon is too heavy for this style. Please consider making it lighter or even removing it:

![toast-border](https://user-images.githubusercontent.com/752610/52074949-a9ecf180-2550-11e9-96b2-8049a9fb67d4.png)

For **actionable** toasts, I also think that the `Action` button is too close to dismiss `×` button, suggest aligning toast actions to left. May prevent accidental toast dismisses when user wants to do an action in the toast.

**Toast stacking** looks great, but i'm not sure about `N more notifications` message. I just don't feel like knowing the number of actual messages is relevant to the user. This will also make Toast component more complicated – it has to know about other toasts in the stack instead of simply being responsible for displaying the message.

**Comment by soumya-ashok** [comment] 2019-01-31 19:22
Thanks for the feedback @belbiy - will work on changes.

**Comment by brendanfalkowski** [comment] 2019-01-31 19:48
@belbiy — Good points, I agree:

- Border — Has too much visual weight. I would remove it and use whitespace for separation.
- Action — Left alignment improves clickable area. Doesn't look like a link or button as styled.
- Stacking — Making people traverse notifications feels like a chore. The app (by design) probably shouldn't ever pop more than two notifications at once, and it'd be fine to stack them in that case.

@soumya-ashok  — I wrote a similar "notify" pattern that handles stacking and supports several extra states, persistence, positioning of the notification, and rich(er) content. I use this a lot for passive notifications of AJAX events (ex: add to cart succeeded).

Demo: https://www.carrierenterprise.com/design/patterns/interactive/notify/
Code: https://github.com/gravitydepartment/notify 

Mine didn't use icons, but I like seeing that for the online/offline status.

Maybe consider pulling the state coloration off the background to alleviate some color conflicts with linked text or buttons.

**Comment by soumya-ashok** [comment] 2019-01-31 20:55
@brendanfalkowski Thanks for weighing in, all great points!
Will have a look at your examples.

**Comment by awilcoxa** [comment] 2019-02-27 21:53
moving to hold while we prioritize 2.3.1 effort

**Comment by soumya-ashok** [comment] 2019-05-10 18:29
@sirugh Updated mockup

![toasts-notifications](https://user-images.githubusercontent.com/25960021/57548842-99a29a80-7327-11e9-80e0-87b4dc6a018c.png)

**Comment by soumya-ashok** [comment] 2019-05-10 19:13
For toasts and notifications other than online/offline

- Lets set it so that dismissible toasts also self-destruct after 7 seconds for now - we can test and change this later if needed

- If the same notification needs to show up repeatedly (repeated error or action confirmation)  reset timeout, potentially a flash of border to indicate that the toast reset so the user has a response associated with their request

For online/offline toasts
Mockups: https://magento.invisionapp.com/share/J8RYQ176SVB

- Same treatment for repeated toasts as for the others (reset timeout + flash)

- The offline toast shows up along with an icon in the header. The toast self-destructs after the appointed time but the icon persists as long as the system is offline. When the online toast shows up, the icon disappears and the online toast also self-destructs after the appointed time.

Let me know if we need to discuss this further.

**Closed** 2019-06-03 19:43 UTC
Labels: enhancement, pkg:peregrine, pkg:venia-concept
