### ISSUE TITLE
Can not reload category page level 3 (Client.js Not found)

### ISSUE THREAD

**Issue by herobk** [magento-research/pwa-studio#1122] opened 2019-04-07 04:18 UTC
I just have customized the category tree to show all categories.
![image](https://user-images.githubusercontent.com/13052885/55678564-48694a80-5926-11e9-8198-7d07d5fdde72.png)
This is our demo.
http://b2bdemo.tigren.com/
I can go to child category when click link on category tree.
But If reload, i get the white page with some error : CLIENT.JS NOT FOUND
![image](https://user-images.githubusercontent.com/13052885/55678609-c75e8300-5926-11e9-9179-7bd20465f97a.png)

Did anyone get this problem ?
Thank you !

**Comment by awilcoxa** [comment] 2019-05-31 20:40
Believe this is related to the same issue reported in #1256

**Comment by tjwiebell** [comment] 2019-05-31 21:11
@awilcoxa - Yep, this is a duplicate of #1256.

**Closed by tjwiebell** 2019-05-31 21:11 UTC
Labels: Troubleshoot
