### ISSUE TITLE
User is unable to scroll to Sign In button on mobile device if there are more categories.

### ISSUE THREAD

**Issue by dpatil-magento** [magento-research/pwa-studio#824] opened 2019-02-05 17:29 UTC
Description:
Mobile specific: When there are more categories user cant scroll to Sign in button. It blocks user from signing to the account.

1. Create more categories which should cross length of mobile device around 8-10. (For iphone SE its 8 or greater).
2. On Venia storefront open Main menu Left drawer and try to scroll to Sign In button.

Expected behavior:
Either user should be allowed to scroll to Sign-in button or the Sign-in button should be always visible at bottom and user should be able scroll the categories.

Actual :
User is unable to scroll to Sign-in button, also it tough to scroll to last category (PFA screen). 

Note - Works fine on browser.

Screen: 
Mobile - 
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/b2ba4d2f-40af-403b-ba34-1e2a76e4f628)

Browser - 
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/19131893-2438-4df6-85d8-b93f9fc760f7)

**Comment by dpatil-magento** [comment] 2019-02-14 22:16
Its now happening on Shipping Address section also.

**Comment by awilcoxa** [comment] 2019-04-29 21:20
duplicate of #1071

**Closed by awilcoxa** 2019-04-29 21:20 UTC
Labels: bug
