### ISSUE TITLE
main.CRITICAL: File 'pub/media/catalog/product//6/3/634754808_640.jpg' was not found or has read restriction.[BUG]

### ISSUE THREAD

**Issue by dereklew** [magento-research/pwa-studio#911] opened 2019-02-18 08:57 UTC
**Describe the bug**
After installing Magento 2.3.0 and PWA Studio, and loaded the Venia demo data, I got these exceptions.

[2019-02-18 02:35:21] main.CRITICAL: File 'pub/media/catalog/product//6/3/634754808_640.jpg' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'pub/media/catalog/product//6/3/634754808_640.jpg' was not found or has read restriction. at /var/www/html/magento2/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:210)"} []
[2019-02-18 02:35:22] main.CRITICAL: File 'pub/media/catalog/product//6/3/634754571_640.jpg' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'pub/media/catalog/product//6/3/634754571_640.jpg' was not found or has read restriction. at /var/www/html/magento2/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:210)"} []
[2019-02-18 02:35:22] main.CRITICAL: File 'pub/media/catalog/product//6/3/634754854_640.jpg' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'pub/media/catalog/product//6/3/634754854_640.jpg' was not found or has read restriction. at /var/www/html/magento2/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:210)"} []
[2019-02-18 02:35:23] main.CRITICAL: File 'pub/media/catalog/product//6/3/635172530_640.jpg' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'pub/media/catalog/product//6/3/635172530_640.jpg' was not found or has read restriction. at /var/www/html/magento2/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:210)"} []
[2019-02-18 02:35:24] main.CRITICAL: File 'pub/media/catalog/product//6/3/634754677_640.jpg' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'pub/media/catalog/product//6/3/634754677_640.jpg' was not found or has read restriction. at /var/www/html/magento2/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:210)"} []
[2019-02-18 02:35:24] main.CRITICAL: File 'pub/media/catalog/product//6/3/634754610_640.jpg' was not found or has read restriction. {"exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): File 'pub/media/catalog/product//6/3/634754610_640.jpg' was not found or has read restriction. at /var/www/html/magento2/vendor/magento/module-catalog-import-export/Model/Import/Uploader.php:210)"} []

**To Reproduce**

**Expected behavior**

able to see the Venia demo images at the frontend.

**Screenshots**
![2019-02-18_17-01-36](https://user-images.githubusercontent.com/15852228/52939396-0f3d4100-339f-11e9-8be8-83af1d26b2b4.png)

**Please complete the following device information:**
 - Device: [e.g. iPhone6, PC]
 - OS: [e.g. iOS8.1, Windows 10] Ubuntu
 - Magento Version 2.3.0
 - NPM version `npm -v`
 - Node Version `node -v`

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Comment by cnu115** [comment] 2019-02-18 12:51
Hey @dereklew try to give server root path till **pub** then try

**Comment by dereklew** [comment] 2019-02-18 13:10
Hi @cnu115 can you elaborate more?

**Comment by cnu115** [comment] 2019-02-18 13:38
Hi @dereklew. In virtual host give back-end magento server url till pub.In my local system i am using apache2.
see the example 
$cd /etc/apache2/sites-enabled
$nano site-name.conf

then change back-end server path 

 <Directory /var/www/html/magento2.3/pub/ >
               Options Indexes FollowSymLinks
               AllowOverride All
               Require all granted
  </Directory>

**Comment by dereklew** [comment] 2019-02-18 13:55
Hi @cnu115 thanks, it works!

**Comment by mhhansen** [comment] 2019-02-18 17:25
closing since it's confirmed as a resolved.
thanks for the help provided @cnu115!
@dereklew feel free to open up again if issue still persists.

**Closed by mhhansen** 2019-02-18 17:25 UTC
Labels: bug
