### ISSUE TITLE
[Styles]: Cart footer actions displays in row instead of column

### ISSUE THREAD

**Issue by vitalics** [magento-research/pwa-studio#629] opened 2018-12-10 14:08 UTC
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
Cart actions display in a row instead of the column as a provided attachment:
![image](https://user-images.githubusercontent.com/8816260/49737380-c6ca1e80-fc9d-11e8-8e3b-3b6bea6c4f49.png)

## Expected result:
Action must displays in a column:
![image](https://user-images.githubusercontent.com/8816260/49737426-e82b0a80-fc9d-11e8-8697-d4e42fc13073.png)

## Possible solutions:
in a `form-body` write next styles:
``` css
.form-body{
    /** was empty */
    display: flex;
    flex-direction: column;
}
```

**Comment by codeAdrian** [comment] 2018-12-10 14:19
Duplicate of the issue: https://github.com/magento-research/pwa-studio/issues/627

PR submitted: https://github.com/magento-research/pwa-studio/pull/628

**Comment by ericerway** [comment] 2018-12-10 14:20
Agreed with @codeAdrian -- duplicate, marking as closed. Thanks.

**Closed by ericerway** 2018-12-10 14:20 UTC
Labels: duplicate
