### ISSUE TITLE
[BUG] Cropped shopping cart in Venia for larger phones

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-studio#1071] opened 2019-03-27 15:36 UTC
Checkout button is cropped in Venia with larger phones including iPhone XR. Safari navigation covers this next step in the checkout process and needs to be aware relative to it's own navigation. 

**URL tested:** https://veniapwa.com/jillian-top.html

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XR&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fveniapwa.com%2Fjillian-top.html&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://veniapwa.com/jillian-top.html) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XR |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 828 x 1792 px |
| Screen size | 6.1 in - 2.56 x 5.54 in |
| Viewport | 414 x 896 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/17dd049771d72818cfcc4602824ae2f399aa3b67/realios_iPhone_XR.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/17dd049771d72818cfcc4602824ae2f399aa3b67/realios_iPhone_XR.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device=iPhone+XR&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fveniapwa.com%2Fjillian-top.html&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://veniapwa.com/jillian-top.html) to reproduce the issue on Browserstack**

**Comment by sirugh** [comment] 2019-03-27 15:41
Ew. Probably https://css-tricks.com/the-trick-to-viewport-units-on-mobile/ ?

**Comment by zetlen** [comment] 2019-04-18 11:49
Some additional context from #1114 which I've closed as a duplicate of this:

**Screenshots of iOS and Android simulators**
![image](https://user-images.githubusercontent.com/1643758/55581809-714dcd80-56e3-11e9-90c5-21c65c9f8496.png)
![image](https://user-images.githubusercontent.com/1643758/55581879-9d694e80-56e3-11e9-8386-3760025e439d.png)

**Additional context**
Modern browser frames expand and contract in response to gestures. They also have partial transparency, which requires rendering a portion of the viewport under them. Layouts like flex and grid often expect to calculate their interior dimensions using the exact viewport height, so this measurement is very important. Browser vendors have conferred about it, and have settled on using the [largest measurement](https://css-tricks.com/the-trick-to-viewport-units-on-mobile/) possible, which is a more broadly compatible, if imperfect, solution.

**Possible solutions**
- A Peregrine hook to subscribe full-height elements to resize events and measure `window.innerHeight` (@jimbo may have input on whether this fits Peregrine's new roadmap)
- Using overflow-y: scroll wherever possible
- Placing call-to-action elements like buttons within a more restricted area of the viewport, like TV production uses a [safe area](https://en.wikipedia.org/wiki/Safe_area_(television)#Action_safe_area) for important content

**Comment by dpatil-magento** [comment] 2019-07-22 20:14
@jimbo @sirugh Please check below observations -
1.  Desktop chrome browser > Home page, search results, category page shifts left on accessing Left/Right drawer.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/e3fbfdaa-cb43-4b57-bde2-ad0ba680ad7b)

2. On Android - When user access shipping form and tap on Name field - Form shifts up and user cant see whats being typed. (Tried on actual device and also on browser stack virtual device.  )

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/a598b5bd-69fd-44ec-8776-4f52a1b60875)

**Closed** 2019-07-25 16:12 UTC
Labels: bug, good first issue, help wanted
