### ISSUE TITLE
npm install error/failed 

### ISSUE THREAD

**Issue by KirillStativka** [magento-research/pwa-studio#236] opened 2018-08-16 15:02 UTC
Hi all ! i have problem with install PWA studio , after clone im try to npm install and its was failed :

> @magento/pwa-studio@ build D:\xamp\htdocs\vuestore.local\dev-pwa
> lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build

lerna info version 3.0.6
lerna info versioning independent
lerna info filter [ '\'@magento/{pwa-buildpack,peregrine}\'' ]
lerna ERR! EFILTER No packages remain after filtering [ '\'@magento/{pwa-buildpack,peregrine}\'' ]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @magento/pwa-studio@ build: `lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @magento/pwa-studio@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

-------------------------------------

node v8.11.4
npm 6.4.0
platform windows 10

Did somebody have same problem ?

**Comment by KirillStativka** [comment] 2018-08-17 06:54
More infromtaion from error log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\xamp\\htdocs\\vuestore.local\\dev-pwa\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.12
3 info using node@v8.11.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild @magento/pwa-studio@
6 info build @magento/pwa-studio@
7 verbose unsafe-perm in lifecycle true
8 info @magento/pwa-studio@ Failed to exec build script
9 verbose stack Error: @magento/pwa-studio@ build: `lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\xamp\htdocs\vuestore.local\dev-pwa\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:126:13)
9 verbose stack     at EventEmitter.emit (events.js:214:7)
9 verbose stack     at ChildProcess.<anonymous> (D:\xamp\htdocs\vuestore.local\dev-pwa\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:126:13)
9 verbose stack     at ChildProcess.emit (events.js:214:7)
9 verbose stack     at maybeClose (internal/child_process.js:925:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
10 verbose pkgid @magento/pwa-studio@
11 verbose cwd D:\xamp\htdocs\vuestore.local\dev-pwa
12 error Windows_NT 10.0.17134
13 error argv "C:\\Program Files\\nodejs\\node.exe" "D:\\xamp\\htdocs\\vuestore.local\\dev-pwa\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v8.11.4
15 error npm  v2.15.12
16 error code ELIFECYCLE
17 error @magento/pwa-studio@ build: `lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build`
17 error Exit status 1
18 error Failed at the @magento/pwa-studio@ build script 'lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build'.
18 error This is most likely a problem with the @magento/pwa-studio package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs @magento/pwa-studio
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls @magento/pwa-studio
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by ontwerps** [comment] 2018-09-05 14:14
Same problem
node v8.11.4
npm 5.6.0
platform windows 10

**Comment by mhhansen** [comment] 2018-09-17 21:30
I was able to reproduce this one by running `npm install` right after the `git clone`
will be trying to find the root cause

<img width="932" alt="screen shot 2018-09-17 at 6 28 44 pm" src="https://user-images.githubusercontent.com/1625755/45651361-b0019a80-baa7-11e8-814c-c37d2ba5ae7b.png">

**Comment by mhhansen** [comment] 2018-09-18 12:37
@KirillStativka would you mind updating the issue title to specify this is something that happens over Win OS? so it's easy to catch for others under same conditions;

It seems to be related to the single-quote char `'`, within the `build` command (and also the `clean` command).

Please go an edit the `build` script (in `package.json`), by doing:
```
# in `package.json` file, replace this line:
"build": "lerna --scope '@magento/{pwa-buildpack,peregrine}' exec -- npm run build",

# with this one:
"build": "lerna --scope \"@magento/{pwa-buildpack,peregrine}\" exec -- npm run build",
```

**after code change**
by running either `npm install` or `npm run build`, node process shouldn't break in the same way as previous comment (it may break related to code stuffs, there are some merges going on these days... but shouldn't be caused by _lerna filtering package_ thing)


---
**debug + root cause, within lerna**

for some reason, `filterPackages` from `lerna`, behaves in a different way under Windows:
```
# node_modules/@lerna/filter-packages/filter-packages.js
function filterPackages(packagesToFilter, include = [], exclude = [], showPrivate) {
  const filtered = new Set(packagesToFilter);
  const patterns = [].concat(arrify(include), negate(exclude));
```
If `build` command is using `'`, the line that creates `patterns` will be ending up with an array containing wrong packages names and filter will fail to retrieve `@magento/peregrine` and `@magento/pwa-buildpack`.

```
## lerna, filterPackages `patterns` constant:

# on OSx
[ '@magento/{pwa-buildpack,peregrine}' ]

# on Windows - my case
[ '\'@magento/{pwa-buildpack,peregrine}\'' ]

# on Windows - issue description case:
 [ ''@magento/{pwa-buildpack,peregrine}'' ]
```

**Comment by sunilit42** [comment] 2018-09-18 13:00
hello, thanks @mhhansen 

https://www.screencast.com/t/dPtaJYslVp

i am facing one more issue

**Comment by mhhansen** [comment] 2018-09-18 17:47
@sunilit42 yes, got the same as you after full run.
same issue with single quote as before `'`, but this time within the `pwa-buildpack/package.json`.

please, try these change:
```
# file packages/pwa-buildpack/package.json
# in `build` script:
"build": "babel src --out-dir dist --ignore '__tests__/,__mocks__/,__fixtures__/' --source-maps --copy-files",

# replace it with:
"build": "babel src --out-dir dist --ignore \"__tests__/,__mocks__/,__fixtures__/\" --source-maps --copy-files",
```

**Comment by sunilit42** [comment] 2018-09-19 08:17
@mhhansen  @KirillStativka 
thanks for your help

One more error
https://www.screencast.com/t/1QvyiRXozJtG

**Comment by sunilit42** [comment] 2018-09-19 08:30
Note :- i am running npm start command from  venia folder \pwa-studio\packages\venia-concept 

It is fixed by below command 

npm install --save-dev gulp-babel @babel/core @babel/preset-env


then after facing another issue

https://www.screencast.com/t/oE0wDxY2uh

when try to install
npm install --save-dev babel-core
npm WARN css-loader@1.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

hope some one provide solution

**Comment by sunilit42** [comment] 2018-09-19 08:43
sorry still issue is there
One more error
https://www.screencast.com/t/1QvyiRXozJtG

**Comment by sunilit42** [comment] 2018-09-19 20:09
any update?

**Comment by sunilit42** [comment] 2018-09-24 14:35
any update on that? 

seems like pwa will not work for window 👎

**Comment by mhhansen** [comment] 2018-09-25 19:33
@sunilit42 release 0.x doesn't work on windows (due to some dependencies/commands that relies on UNIX shell). many scripts expect to run within a UNIX shell, so maybe a workaround for your case could be the `Windows Subsystem for Linux` using an Ubuntu distro.
I gave that a try and (within the VM that I got installed to give some feedback to you), installed ubuntu and get all dependencies installed correctly.
I know this may be a pain for you, but it's the most accurate feedback that I can give you for the time being. I'd expect that `1.x release` with the new UPWARD architecture, address some of this troubles, but can't confirm now.

right now there are a few changes over `master` due to all the architecture changes that are going on, so if you face a build error or the webpack server fails, keep in mind to frequently download latest commits from `master`. this is also something that will change in the near future.

**here are some reference links**
https://docs.microsoft.com/en-us/windows/wsl/install-win10
https://docs.microsoft.com/en-us/windows/wsl/initialize-distro

also put together a few commands that may help, in case you download ubuntu:
```
# create/clone project folder
cd /var
sudo mkdir www
cd www/
sudo git clone https://github.com/magento-research/pwa-studio.git
chown -R ubuntu:ubuntu pwa-studio/

# install nodejs + npm
sudo apt install curl
curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -
sudo apt install nodejs

# check versions (reboot ubuntu if you get `not command found`)
node -v
npm -v

# within pwa-studio folder
npm install
```

**leave you some shots of the process in case it helps:**
![01](https://user-images.githubusercontent.com/1625755/46036987-4738a480-c0dd-11e8-800b-e00d13b40cd2.png)
![02](https://user-images.githubusercontent.com/1625755/46036991-4a339500-c0dd-11e8-8f98-9bbf1f9f6025.png)
![03](https://user-images.githubusercontent.com/1625755/46036995-4bfd5880-c0dd-11e8-96ca-e0e8fd59124b.png)
![04](https://user-images.githubusercontent.com/1625755/46037008-5586c080-c0dd-11e8-9eba-8f7285d754b3.png)
![05](https://user-images.githubusercontent.com/1625755/46037013-59b2de00-c0dd-11e8-8bbd-6ec1b0f5ecd8.png)
![06](https://user-images.githubusercontent.com/1625755/46037016-5d466500-c0dd-11e8-92a6-a2c28cab0b16.png)
![07](https://user-images.githubusercontent.com/1625755/46037022-60d9ec00-c0dd-11e8-8ad9-666f027db7e0.png)
![08](https://user-images.githubusercontent.com/1625755/46037029-659ea000-c0dd-11e8-8c5f-b1ac9d2456a6.png)

**Comment by sunilit42** [comment] 2018-09-26 08:27
![image](https://user-images.githubusercontent.com/2923438/46067301-21220b80-c194-11e8-9822-ee24e799cfc1.png)


still issue :)

**Comment by mhhansen** [comment] 2018-09-26 21:18
> still issue :)

yes, sunil.
you'll face this kind of situations till we can get a stability in `0.x` or, when `1.x` gets released.
meanwhile, this #236 will occur due to the high activity on the architecture.

**Comment by sunilit42** [comment] 2018-10-04 13:02
@mhhansen 
let me know when i can check again

**Comment by sunilit42** [comment] 2018-10-11 11:32
@mhhansen 

any update on this?

**Comment by sunilit42** [comment] 2018-11-02 14:32
@mhhansen  any update?

**Comment by zetlen** [comment] 2018-11-02 14:37
@sunilit42 Your most recent error seems to be due to an older version of the .env file. Can you try backing up your `packages/venia-concept/.env` file and copying `packages/venia-concept/.env.dist` to `packages/venia-concept/.env`?

**Comment by mhhansen** [comment] 2018-11-02 17:20
> @mhhansen any update?

@sunilit42 I gave that a try using ubuntu distro with the new `release/2.0` branch.
everything gets install OK until the dev server starts and tries to SSL using `devcert`

I'll try to debug this to see if there's a workaround, if you find one let us know!
<img width="1142" alt="screen shot 2018-11-02 at 2 18 43 pm" src="https://user-images.githubusercontent.com/1625755/47930301-4f3cee80-deaa-11e8-8098-5a0af927d7a1.png">

**Comment by mhhansen** [comment] 2018-11-02 17:48
it seems that when I first ran, I had a thing with my user password, so it half installed the .cert.
* I went with a `rm -Rf /home/ubuntu/.config/devcert` to clean it up.
* then `npm run build` again (but now I put the right password :) )
* lastly `npm run watch:venia` to get the dev server started.

everything ended up smoothly 🍺

<img width="1135" alt="screen shot 2018-11-02 at 2 45 20 pm" src="https://user-images.githubusercontent.com/1625755/47931595-0850f800-deae-11e8-9157-38adf5552aaf.png">

let me know how it went on your end

**Comment by sunilit42** [comment] 2018-11-05 12:18
@mhhansen 


ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "import-graphql" specified in "base" at 6, attempted to resolve relative to "/var/www/pwa-studio/packages/venia-concept/src"
    at /var/www/pwa-studio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/var/www/pwa-studio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/var/www/pwa-studio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/var/www/pwa-studio/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/var/www/pwa-studio/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/var/www/pwa-studio/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/var/www/pwa-studio/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/var/www/pwa-studio/node_modules/babel-loader/lib/index.js:50:20)
    at /var/www/pwa-studio/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/var/www/pwa-studio/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
npm ERR! code ELIFECYCLE

**Comment by mhhansen** [comment] 2018-11-05 12:49
did you do a fresh clone of the repo and followed the new setup?
https://magento-research.github.io/pwa-studio/venia-pwa-concept/setup/

**Comment by mhhansen** [comment] 2018-11-21 09:58
please if there are still issues regarding the ubuntu distro approach, open up a new issue providing steps to reproduce. closing this for now, thanks!

**Closed by mhhansen** 2018-11-21 09:58 UTC
