### ISSUE TITLE
[Bug] Validation error on create account page is not reseted

### ISSUE THREAD

**Issue by Starotitorov** [magento-research/pwa-studio#420] opened 2018-10-25 09:10 UTC
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3  |
| Operating System + version  | Ubuntu 18.04  |
| node.js version (`node -v`) | 8.12.0  |
| npm version (`npm -v`)      | 6.4.1  |

## Description

Open create account form in drawer. Fill form fields with an error, enter, for example, password that does not satisfy requirements, press submit button. You should see validation error at the bottom. Close drawer and open it again. You should still see that validation error and form in general was not cleared.

![create-account-drawer-error](https://user-images.githubusercontent.com/11873143/47488358-dd7ef800-d84c-11e8-8aac-523392c86688.PNG)

The issue is not related only to this particular case, in general, we store validation error in user domain, that is a common domain. Recently we implemented create account page, here you can reproduce the bug too.
1. Enter invalid data in the form fields.
2. Press submit button.
3. See validation error.
4. Go to home page using logo in header.
5. Make another order using checkout flow.
6. Press create account button on the order confirmation page.

The application will navigate you to create account page and you will see the following:

![create-account-error](https://user-images.githubusercontent.com/11873143/47487953-21253200-d84c-11e8-867d-fe061d6add1e.PNG)

@ericerway, @zetlen, please, approve that this is a bug and should be fixed.

## Expected result:

Validation error and form values should be reseted when user close create account form and open it again.

## Possible solutions:

The source of the problem, in my opinion, is our invalid separation of Redux store into domains. createAccountError should be a part of separate domain for create account form, in this case it will be easier to manage this domain, we will be able to reset it in componentWillUnmount lifecycle method. We do not have reasons to store this server validation error inside user domain.

By the way, if we decide to user redux-form it will provide the solution for such use cases out of the box. Redux-form provides [SubmissionError](https://redux-form.com/7.4.2/docs/api/submissionerror.md/).

**Comment by pcvonz** [comment] 2018-10-29 19:01
Note that server message at the bottom is just placeholder. I believe the actual success/error/warning message component is still being designed.

@JStein92 did a lot of work on the form component, so he might be able to give some input on Redux-Form.

**Comment by JStein92** [comment] 2018-10-29 19:08
In this case, the component is not being mounted/unmounted, just hidden/shown. If the only issue here is the server message not hiding, I don't think this issue is needed, since that message is a placeholder.

**Comment by awilcoxa** [comment] 2019-01-09 17:08
Should have been resolved by previous field changes. Should attempt to replicate and if we can't then close this out.

**Comment by dpatil-magento** [comment] 2019-02-05 02:37
@awilcoxa  this issue is reproducible on for sign-in flow if user enters invalid username/pwd and clicks on sign-in button.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/3f8acbdc-f32f-49e6-9294-864085181617)

**Comment by awilcoxa** [comment] 2019-05-06 15:19
Attempted to replicate given new changes to form field validations and error states and seem to no longer be valid. If anyone can replicate please re-open, otherwise closing this as a non-issue.

**Closed by awilcoxa** 2019-05-06 15:19 UTC
Labels: bug
