### ISSUE TITLE
I am trying to modify the ui component under venia-concept, and the page refresh error is reported after saving.

### ISSUE THREAD

**Issue by threescs** [magento-research/pwa-studio#1254] opened 2019-05-20 02:51 UTC
![image](https://user-images.githubusercontent.com/29721759/57993798-10405480-7aed-11e9-8bbf-c6903184df34.png)

Expected: Normal compilation run
Actual: The page reported that the js under dist could not be found.

**Comment by niklas-wolf** [comment] 2019-05-28 14:46
https://github.com/magento-research/pwa-studio/issues/1256 It's the exact same Bug ;)

**Comment by awilcoxa** [comment] 2019-05-31 20:19
closing this issue as a duplicate of #1256

**Closed by awilcoxa** 2019-05-31 20:19 UTC
Labels: bug
